### ISSUE TITLE
parsing multiple tags in one pass

### ISSUE THREAD

**Issue by luck02** [coolbong/node-tlv#1]
Hi, when we receive tags back from our partner they come in a stream.  All tags in one data field.

I had assumed that this library will parse them out into a collection but it seems to only parse the first from the stream and then discard the rest.  It would seem an easy fix, if I were to make a pull request would that be accepted?  eg:
4F07A00000000310105F2403221231
would return 2 tags 4F07 and 5F24 rather than just 4f07 and tossing the other tag out.

Thanks,

**Comment by luck02** [comment]
Here's one way to do it, but I think it should be in the TLV library:
```
    const rawTlvFixtures = '4F07A00000000310105F2403221231';
    const t1 = nodeTlv.parse(rawTlvFixtures);
    const t2 = nodeTlv.parse(rawTlvFixtures.substring(r1.getSize()*2));
```
But I think it should be part of the library, a parseMultipleTLV function that could track the current offset and insert the results into an array and return the array.

**Comment by coolbong** [comment]
I added new API for this issue.

Check this API TLV.parseList()


`      var list = TLV.parseList('4F07A00000000310105F2403221231');

        var firstTag = list[0];

        assert(firstTag.getTag() === '4F');
        assert(firstTag.getLength() === 7);
        assert(firstTag.getValue() === 'A0000000031010');

        var secondTag = list[1];
        assert(secondTag.getTag() === '5F24');
        assert(secondTag.getLength() === 3);
        assert(secondTag.getValue() === '221231');`

**Comment by luck02** [comment]
Thanks.  👍
